### ISSUE TITLE
Can I use navigation without hash(# symbol)?

### ISSUE THREAD

**Issue by Nandiin** [elm-lang/navigation#11]
I'd like a hash-free navigation.
Ex:
`https://localhost:8000/Counter.elm/0` 
`https://localhost:8000/Counter.elm/1` 
etc. for this repo's example

I've tried to modify the Counter.elm to achieve this and failed. 
```
toUrl count = 
  "/" ++ toString count
fromUrl url = 
  String.toInt (String.dropLeftt 1 url)
```
This will cause a dead-loop(maybe) when using elm-reactor.
When it is compiled to html, it worked partially. The feature is achieved, but the sub-path is overridden:
The compiled html is at `localhost/some/path/counter.html`, and when the app starts, the address will be overridden to `localhost/0`, `localhost/1`, etc. But I want it to be something like `localhost/some/path/counter.html/0`

**Comment by simonh1000** [comment]
duplicates: https://github.com/elm-lang/navigation/issues/3 

It can be used with html routes - I do it - but you have you have to get your code perfectly correct, otherwise is crashes badly. I ended up editing the url-parser source code to read

```
parse : formatter -> Parser formatter a -> String -> Result String a
parse input (Parser actuallyParse) url =
  case actuallyParse (Chunks [] (String.split "/" url |> List.filter ((/=) ""))) input of
```

**Comment by evancz** [comment]
You can parse a `Location` however you want. All the data about the URL is in there.

In the upcoming release, this will be easier to extract with `parsePath` and `parseHash` in `evancz/url-parser`.

Until then, I think this question would be better for elm-discuss or the slack channel.
