### ISSUE TITLE
Documentation: Mention that URL parser gets run on init?

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/navigation#12]
Currently, all the documentation explicitly says about how the URL parser impacts the program is:

>  Whenever this library changes the URL, the parser you provide will run. 

Implicitly, from a note furter below in the documentation, it also becomes clear that the URL parser also gets run when the URL changes not as an action of this library, but instead as a user action with back and forward buttons.

But nowhere does the doumentation imply that the URL parser also gets run on initialization of the program, with the URL at which the program was loaded. Which was a problem here: https://groups.google.com/d/msg/elm-discuss/ySsSlT9zcKg/nSA-diaLAAAJ. From that post:

> So it turns out the urlParser you hand to Navigation.program gets invoked on the initial URL before the call to init happens, and the output of urlParser feed into init.  This was not obvious to me from the documentation nor the examples I found, which are more about setting the URL or responding to URL monkeying.

**Comment by evancz** [comment]
It doesn't work like this anymore. The `init` will just get the `Location` directly.

**Comment by skinnyjames** [comment]
Apologies if this has already been answered, but
How does one trigger a url change on a page load?
