### ISSUE TITLE
Best way to handle clicks on hashless URLs?

### ISSUE THREAD

**Issue by domenkozar** [elm-lang/navigation#13]
I'd like to achieve the following:
- use `navigation` to handle SPA
- use "normal" urls using history api
- still have URL hints and being able to open them in new page using ctrl-click

Currently, I should be able to achieve that using:

``` elm
a
  [ onPreventDefaultClick NewPage
  , href "/newpage" ]
  [ text "foobar" ]
```

where `onNonPropagatedClick` would set `preventDefault` to true.

Should `navigation` support this pattern better?

Refs https://github.com/domenkozar/hydra-frontend/issues/5

**Comment by domenkozar** [comment]
I've implemented first draft in https://github.com/domenkozar/hydra-frontend/pull/7, but it's still not perfect.

**Comment by sircharleswatson** [comment]
@domenkozar I made [this](https://github.com/sircharleswatson/elm-navigation-example) about 3 months ago. I haven't done any elm since then but I think it's probably still mostly up-to-date.

**Comment by woylie** [comment]
I'm currently using the implementation suggested by @sircharleswatson above. It uses the following function:

```
clickTo : String -> List (Attribute Msg)
clickTo path =
  [ href path
  , onWithOptions
      "click"
      { stopPropagation = True, preventDefault = True }
      (Json.map (\_ -> Go path) Json.value)
  ]
```

Links can then be written as:

```
a (clickTo "/my/path") [ text "whatever" ]
```

However, ctrl-click resp. cmd-click still don't work with this implementation. Does anybody know how to make this work properly? An eventual package level solution without having to define clickTo would be even better.

**Comment by jvdvleuten** [comment]
I found a piece of code and transformed it using the parser.

Normal URL works and clicking as well.

Using Elm 0.18

**OnClickPage.elm**
```
onPreventDefaultClick : msg -> Attribute msg
onPreventDefaultClick message =
    onWithOptions 
        "click" 
        { defaultOptions | preventDefault = True } 
        (Json.Decode.succeed message)


onClickPage : Page -> List (Attribute Msg)
onClickPage page =
    [ style [ ( "pointer", "cursor" ) ]
    , href (pageToUrl page)
    , onPreventDefaultClick (NewPage page)
    ]
```

**Routing**
```
type Page
    = NotFound
    | Home
    | Register


matchers : Parser (Page -> a) a
matchers =
    oneOf
        [ map Home top
        , map Register (s (pageToUrl Register))
        ]


parseLocation : Location -> Page
parseLocation location =
    case (parsePath matchers location) of
        Just route ->
            route

        Nothing ->
            NotFound


pageToUrl : Page -> String
pageToUrl page =
    case page of
        Home ->
            ""

        Register ->
            "register"

        NotFound ->
            "not-found"
```

**Msg.elm**
```
type Msg
    = NewPage Page
    | NewLocation Location
```

**Main.elm**
```
main : Program Never Model Msg
main =
    Navigation.program NewLocation
        { init = init
        , view = view
        , update = update
        , subscriptions = subscriptions
        }

init : Location -> ( Model, Cmd Msg )
init location =
    let
        currentRoute =
            Routing.parseLocation location
    in
        initialModel currentRoute ! []

initialModel : Routing.Page -> Model
initialModel route =
    { windowSize = { width = 0, height = 0 }
    , page = route
    }

type alias Model =
    { windowSize : Window.Size
    , page : Routing.Page
    }

update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    case msg of
        NewLocation location ->
            let
                newRoute =
                    parseLocation location
            in
                { model | page = newRoute } ! []

        NewPage page ->
            model ! [ Navigation.newUrl (Routing.pageToUrl page) ]
```

**Comment by domenkozar** [comment]
@jvdvleuten does middle clicking work (meaning it opens a new tab)?

**Comment by jvdvleuten** [comment]
Yes it does. Middle clicking, right click and open in new tab.

The way it works is with a "normal" click we send a `NewPage` message which will issue a `Navigation.newUrl (Routing.pageToUrl page)` command. This updates the browser history and provides a new `NewLocation` message. See http://package.elm-lang.org/packages/elm-lang/navigation/2.0.1/Navigation#newUrl.

With a new tab click, parsing works normally as it would have been without the `NewPage` message.

**Comment by domenkozar** [comment]
Wonderful, I'll test this out!

**Comment by woylie** [comment]
That's basically the same as the solution that I posted before, except for cosmetics. So unfortunately, it still doesn't work with Cmd-click on a Mac.

**Comment by jvdvleuten** [comment]
I overlooked the fact you do not want to prevent the link to be opened when ctrl or command key is pressed.

The following change works at my computer using the "ctrl" key. Can you check it works using the "command" key at your mac as well?

Passing a `Json.Decode.fail` will open a new tab when control clicking.

```
onClickPage : Page -> List (Attribute Msg)
onClickPage page =
    [ style [ ( "pointer", "cursor" ) ]
    , href (pageToUrl page)
    , onPreventDefaultClick (NewPage page)
    ]


onPreventDefaultClick : msg -> Attribute msg
onPreventDefaultClick message =
    onWithOptions "click"
        { defaultOptions | preventDefault = True }
        (preventDefault2
            |> Json.Decode.andThen (maybePreventDefault message)
        )


preventDefault2 : Decoder Bool
preventDefault2 =
    Json.Decode.map2
        (invertedOr)
        (Json.Decode.field "ctrlKey" Json.Decode.bool)
        (Json.Decode.field "metaKey" Json.Decode.bool)


maybePreventDefault : msg -> Bool -> Decoder msg
maybePreventDefault msg preventDefault =
    case preventDefault of
        True ->
            Json.Decode.succeed msg

        False ->
            Json.Decode.fail "Normal link"


invertedOr : Bool -> Bool -> Bool
invertedOr x y =
    not (x || y)
```

**Comment by woylie** [comment]
Great, that works. Finally! Thanks!

**Comment by woylie** [comment]
Can we include that in the Navigation package? It seems like a very common requirement.

**Comment by jvdvleuten** [comment]
@woylie What part and how would you like this to include it in the Navigation package? I think we can include some like the `onPreventDefaultClick` in the Html.Events package and include onClickPage in the Html.Attribute package if it is widely used? The problem is all the interaction with routing, navigation, clicking and the message generating a command to change the URL.

Any ideas?

**Comment by woylie** [comment]
You're right, the Navigation package probably isn't the right place for this.

The `onClickPage` function isn't really that important. It also makes some assumptions (`Page` type, `Newpage Page` msg, `pageToUrl Page` function). If you strip it down, you'd end up with something like this:

```
onClickPage : Attribute msg -> String -> List (Attribute Msg)
onClickPage msg url =
    [ href url
    , onPreventDefaultClick msg
    ]
```

This doesn't seem very useful to me as a library function. And if you want to add some more attributes, you would have to write your links like this:

```
a (onClickPage (NewPage "somevalue") "somestring") ++ [target "_blank", style "btn-solid"] [text "abc"]
```

That's kind of ugly. I can do without that.

The `onPreventDefaultClick` function on the other hand would be a great addition to Html.Events. Let's move the discussion there.

**Comment by evancz** [comment]
I like where this ended up, great work!

I'll add a note in the README of this project pointing to the solution in https://github.com/elm-lang/html/issues/110 which seems like the way to go.

I'm working on lots of SPA related things now, so this is in the path of "batched work" for now. It may be a bit before I can merge it into HTML, but it's on the path!

**Comment by evancz** [comment]
Okay, note added to the readme. Thanks again for sorting through this!

**Comment by jonathanfishbein1** [comment]
I'm a bit of a noob with urls, I've almost implemented #-less urls in elm but when I copy/paste or open in a new tab I'm still having some issues when there is a path parameter.  Any ideas? Thanks!
