### ISSUE TITLE
examples/Counter.elm is incompatible with 2.0.0 API changes

### ISSUE THREAD

**Issue by sentience** [elm-lang/navigation#19]
The example included in this repository has not been updated for the Navigation 2.0.0 API changes, and will fail to build with this version of the package.

In particular, Navigation 2.0.0 has done away with `Navigation.Parser`, which Counter.elm uses.

**Comment by evancz** [comment]
That version of the library is not released yet, but thanks for the reminder. Should do this before 0.18 is out.
