### ISSUE TITLE
Doesn't work in IE11 when changing hash

### ISSUE THREAD

**Issue by edmellum** [elm-lang/navigation#20]
IE11 [has a bug](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/3740423/) where changing the hash of a URL doesn't fire a `popstate` event like it should. MS is not going to fix the bug in IE11, but has fixed it in Edge.

This makes using navigation in hashchange environments impossible.

A workaround could be listening to both popstate and hashchange only on IE11. [mjackson/history](https://github.com/mjackson/history) has an [issue on this](https://github.com/mjackson/history/pull/336) that's [solved quite simply](https://github.com/mjackson/history/commit/1370f889784c01d3a16c192e5c1a052310e20a4d).

**Comment by edmellum** [comment]
I've made a workaround in our codebase that forks this library and implements the same solution as mjackson/history does and it works nicely.

**Comment by popara** [comment]
@edmellum can you share the solution please?

**Comment by stil4m** [comment]
@edmellum I'm interested in the solution as well. Running into this as well.

**Comment by popara** [comment]
I am prepping PR for this weekend with the fix.

**Comment by daymosik** [comment]
I had this same problem in IE10 and IE11, and i had to do a special UGLY workaround for this:

```js
window.addEventListener('hashchange', () => window.location.reload());
```

**Comment by edmellum** [comment]
I see the current pull request from @daymosik doesn't address the issue as it creates double routes for every browser but IE. Is the work there going to be finished? If not I might have some time in the near future to open a pull request with the solution I've written that properly solves this.

**Comment by popara** [comment]
https://github.com/elm-lang/navigation/pull/28

**Comment by daymosik** [comment]
@edmellum i've made a fix in my PR after which it will not create double routes, but i know it could be written in better way, but i'm not an elm expert yet and i have no idea how i could write this without this one line i made a comment about.
