### ISSUE TITLE
Fail more gracefully on parse error?

### ISSUE THREAD

**Issue by simonh1000** [elm-lang/navigation#3]
I would prefer to use HTML5 URLs so I changed the example code to
```
toUrl : Int -> String
toUrl count =
  "/counter/" ++ toString count
  -- "#/" ++ toString count


fromUrl : String -> Result String Int
fromUrl url =
  String.toInt (String.dropLeft 2 url)
  -- String.toInt (String.dropLeft 9 url)


urlParser : Navigation.Parser (Result String Int)
urlParser =
  -- Navigation.makeParser (fromUrl << .hash)
  Navigation.makeParser (fromUrl << .pathname)
```
And the page just hangs (nothing on screen, but url of `/counter/0` in elm-reactor and if you elm-make it. Only when I changed 2 to 9 did it work.

**Comment by evancz** [comment]
I can't tell how the title of this relates to the body. Give an http://sscce.org/ or clarify your motivation in a new issue.
