### ISSUE TITLE
Failing to Parse search properly

### ISSUE THREAD

**Issue by wittjosiah** [elm-lang/navigation#33]
When search string comes after hash it fails to parse properly into location type. If search string comes before hash it successfully parses into location type. For example:

hitting this url `"http://localhost:9000/#dashboard?search=jiwoejfj"` gives me

    { href = "http://localhost:9000/#dashboard#?search=jiwoejfj"
    , host = "localhost:9000"
    , hostname = "localhost"
    , protocol = "http:"
    , origin = "http://localhost:9000"
    , port_ = "9000"
    , pathname = "/"
    , search = ""
    , hash = "#dashboard#?search=jiwoejfj"
    , username = <internal structure>
    , password = <internal structure>
    }

while hitting this url `"http://localhost:9000/?search=jiwoejfj#dashboard"` gives me

    { href = "http://localhost:9000/?search=jiwoejfj#dashboard"
    , host = "localhost:9000"
    , hostname = "localhost"
    , protocol = "http:"
    , origin = "http://localhost:9000"
    , port_ = "9000"
    , pathname = "/"
    , search = "?search=jiwoejfj"
    , hash = "#dashboard"
    , username = <internal structure>
    , password = <internal structure>
    }

I was able to get this result above with Elm 0.18 in Chrome, Firefox and Safari

**Comment by OvermindDL1** [comment]
What is the problem?  The URL of `http://localhost:9000/#dashboard#?search=jiwoejfj` should indeed have the hash of `#dashboard#?search=jiwoejfj` as the hash is defined as the part of the url that starts with a `#` to the end of the url.

And indeed, I just tested in chrome, the `location.hash` is indeed `#dashboard#?search=jiwoejfj` for the URL of `http://localhost:9000/#dashboard#?search=jiwoejfj`.

For note, as you can see at https://github.com/elm-lang/navigation/blob/master/src/Native/Navigation.js#L73-L85 for example, Navigation is not parsing the URL itself, it is using the browser's `window.location` object directly and just grabbing the values from it.  This is how the browser parses it as this is how the Spec for URL's defines it should be parsed.

Or is the issue really you are going to the URL of `http://localhost:9000/#dashboard?search=jiwoejfj` but getting the output of `http://localhost:9000/#dashboard#?search=jiwoejfj`, which definitely should not be happening...

**Comment by wittjosiah** [comment]
@OvermindDL1 Oops, the second `#` is a typo. I should be `http://localhost:9000/#dashboard?search=jiwoejfj`. Regardless, you're right and the location type is accurately reflecting `window.location` so my issue must be elsewhere. Thanks!

**Comment by kiambogo** [comment]
Looks like an issue with the url parser: https://github.com/evancz/url-parser/issues/27
