### ISSUE TITLE
Direct urls doesn't work on Heroku

### ISSUE THREAD

**Issue by anildigital** [elm-lang/navigation#38]
https://ruby-operators.herokuapp.com/spaceship directly doesn't work but works when visited via https://ruby-operators.herokuapp.com/ 

Is this Heroku issue or something missing related to navigation work fine on Heroku?

Source code - https://github.com/anildigital/ruby-operators

**Comment by zwilias** [comment]
Hi @anildigital 

As discussed on Slack: you'll need to instruct your backend to serve the same file for multiple urls.

**Comment by anildigital** [comment]
Thanks @zwilias for instant help!
