### ISSUE TITLE
Scroll state sticks between navigation

### ISSUE THREAD

**Issue by freiguy1** [elm-lang/navigation#43]
When I am scrolled to the bottom of page 1, navigate to page 2, the navigation works perfectly except that my window is scrolled to the bottom on page 2! Is this intended behavior? Do I need to tell the app to scroll to the top upon every navigation? It seems like setting scrolling position to the top at each navigation should be default.

**Comment by evancz** [comment]
I recommend asking about this on https://discourse.elm-lang.org/ or http://elmlang.herokuapp.com/ to get a rough answer. If it ends up being a bug in Elm code, folks in either place can help you figure it out and open an issue specifically about that with an SSCCE.
