### ISSUE TITLE
It's possible to create a loop with current effects

### ISSUE THREAD

**Issue by domenkozar** [elm-lang/navigation#5]
I've managed to hog my chromium to extent where I had to kill it. It was Elm doing endless loop of changing the url.

It's possible to achieve that currently with following code (I've reduced it to only relevant parts):

```elm
type Page = Home

pageParser : Parser (Page -> a) a
pageParser =
  oneOf
    [ format Home (s "home")  ]

pageToURL : Page -> String
pageToURL page =
  case page of
    Home -> "/"
```

Notice that `Home` is parsed as `/home`, but redirects to `/`. Using the example App, what will happen is that on error it will redirect to current page, which is `/` and it will fail to parse, etc creating a loop.

Let me know if I should clarify some parts or provide a full working example.

**Comment by evancz** [comment]
Seems like your bug. You can create loops with most effects really.

In this case, this library lets you hear about *every* change, and I think that is the correct thing. This means you can centralize all your transition logic instead of having it spread out in 90 places. I'd say, let's see if more people run into this. If it seems like a problem for many folks, we can think about doing something different.

**Comment by domenkozar** [comment]
Understood - I expected that. Just wanted to make sure it's documented for any future references.

**Comment by evancz** [comment]
Where should it be written down? What particular place would have been helpful to you?

**Comment by domenkozar** [comment]
I always read whole documentation, so maybe at the beginning/end of reference documentation since it's relevant for all effects.

**Comment by evancz** [comment]
I put it [here](http://package.elm-lang.org/packages/elm-lang/navigation/1.0.0/Navigation#program) already. That seems like the right place to me.

**Comment by etaque** [comment]
Side note: I avoid this by creating a NotFound special page/route so that I never have to redirect, my url parser is always succeeding.

**Comment by domenkozar** [comment]
Yes, that's what I did at the end. If url parser fails, I display a message to the user (model changes).
