### ISSUE TITLE
Navigation breaks the REPL

### ISSUE THREAD

**Issue by Bogdanp** [elm-lang/navigation#7]
Loading any module that imports (directly or not) `Navigation` ends up blowing up in the REPL with:

```
/Users/bogdan/test/repl-temp-000.js:6060
	onDocument: F3(on(document)),
	                  ^

ReferenceError: document is not defined
    at /Users/bogdan/test/repl-temp-000.js:6060:20
    at Object.<anonymous> (/Users/bogdan/test/repl-temp-000.js:6064:2)
    at Object.<anonymous> (/Users/bogdan/test/repl-temp-000.js:7671:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

See https://gist.github.com/Bogdanp/1613141a4e64330b8d4580f3a54b114d for a simple example.

This issue does not occur with `Html.App`.

**Comment by fapian** [comment]
I get the same error, if I try to run tests with https://github.com/elm-community/elm-test.

**Comment by kgashok** [comment]
Me too! What a coincidence!

**Comment by kgashok** [comment]
@fapian  Just now, I was able to resolve this by separating out my model and view components into two separate files, and only including the model into the Test elm file.

**Comment by gkubisa** [comment]
I also got this issue in my elm tests and came up with a workaround which does not require any changes to the structure of my app. When executing the tests, I simply ask `node` to preload a module which defines fake `document` and `window` objects in the global scope as follows:

`node -r ./workaround-elm-test-and-navigation.js ./compiled-elm-tests.js`

The content of `./workaround-elm-test-and-navigation.js` is `global.document = global.window = {}`.

**Comment by maruks** [comment]
please fix this bug
