### ISSUE TITLE
Include Location in the Result in urlUpdate

### ISSUE THREAD

**Issue by domenkozar** [elm-lang/navigation#8]
It would be useful to have access to `Navigation.Location` inside the `urlUpdate` function in case of `Err`.

Use case: url parsing fails, but we'd like to show what URL was used to the user in error message.

**Comment by princejwesley** [comment]
As per the [code](https://github.com/elm-lang/navigation/blob/master/src/Navigation.elm#L66), its purely depends on the parser we supplied.

Supply `Navigation.makeParser` a function of type `Location -> Result String (String, Location) ` and capture `Err (msg, location) `  in `urlUpdate` function

**Comment by evancz** [comment]
@princejwesley is correct. The API is flexible enough that you can do this if you want.
