### ISSUE TITLE
Passing flags to parser

### ISSUE THREAD

**Issue by sporto** [elm-lang/navigation#9]
I want to use `Navigation.programWithFlags` and pass flags to my Url parser. For example I want to pass `basePath = "app"`.

But I cannot find a way to pass the flags to my parser as I get the flags in `init` and this is too late. Any ideas? 

I think that when using `programWithFlags` the first argument should be a function that takes the flags and returns the parser `flags -> Parser data`.

**Comment by sporto** [comment]
Fixed this by create a parser that just returns the `href` and doing the actual parsing in `urlUpdate`. Doesn't feel great but this works. Still consider this case.

**Comment by bradurani** [comment]
I discovered the same limitation. I want to pass the root path of my SPA as a flag so I can use it in my parser

**Comment by OvermindDL1** [comment]
Also ditto, same issue.  Any update on this?

**Comment by OvermindDL1** [comment]
If `urlParser` could be passed any user-defined thing, or at best the model, that would by far be the best.  Hard to handle parsing in all cases when we do not know our state.

**Comment by AlexKovalevych** [comment]
Any news about this feature? #15

**Comment by evancz** [comment]
The new version has you deal with the `Location` more directly, so I think it'll be less tricky how to do this.
